[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[project]
name = "GkmasObjectManager"
version = "1.5.0"
description = "An object-oriented interface for Gakuen Idolm@ster object manifests and assets"
readme = "README.md"
requires-python = ">=3.12,<3.14"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
authors = [
    { name = "Ziyuan Chen" },
]
dependencies = [
    "cryptography",
    "pandas",
    "Pillow",
    "protobuf",
    "pydub",
    "PyYAML",
    "requests",
    "rich",
    "tqdm",
    "UnityPy",
    "audioop-lts>=0.2.2; python_version >= '3.13'",
    "flask",
]

[project.urls]
Homepage = "https://github.com/AllenHeartcore/GkmasObjectManager"
Repository = "https://github.com/AllenHeartcore/GkmasObjectManager"

[tool.uv.build-backend]
module-name = "GkmasObjectManager"
module-root = ""
